global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'porteight-auth-proxy'
    static_configs:
      - targets: ['auth-proxy:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s 